name: Run tests on push
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List files
        run: ls

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies and run tests
        #working-directory: ./python-code-profile
        run: |
          pipenv install --dev
          pipenv run pytest
